version: 2

project_name: hledger-x

before:
  hooks:
    - rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl arm-unknown-linux-gnueabihf x86_64-apple-darwin aarch64-apple-darwin x86_64-pc-windows-gnu
    - cargo install --locked cargo-zigbuild

builds:
  - id: hledger-x
    builder: rust
    binary: hledger-x
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
      - arm-unknown-linux-gnueabihf
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Target }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - none*

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kfkonrad
    name: hledger-x
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
